version: "3"
services:
  mongodb:
    image: "mongo:6.0.3"
    container_name: aa_dr_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "aa-dr-root"
      MONGO_INITDB_ROOT_PASSWORD: "cpac"
  backend:
    container_name: aa-dr-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - "3001:3001"
    env_file:
      - backend.env
    volumes:
      - ./backend:/app
  frontend:
    container_name: aa-dr-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    depends_on:
      - backend
    ports:
      - "3000:3000"
    env_file:
      - frontend.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
volumes:
  mongodb_data_container:
